# Generated by Django 4.0.2 on 2022-03-07 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_selection_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Объявление'),
        ),
    ]
