# Generated by Django 4.0.2 on 2022-03-07 18:09

# import ads.models
import ads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(default=False, validators=[ads.validators.check_false], verbose_name='Опубликован или нет'),
        ),
    ]
