# Generated by Django 4.0.2 on 2022-02-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_options_alter_cat_options_alter_ad_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ads.cat'),
        ),
    ]
