# Generated by Django 4.0.2 on 2022-02-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_category_id_alter_ad_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.cat', verbose_name='Категория'),
        ),
    ]
