# Generated by Django 4.0.2 on 2022-03-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
