# Generated by Django 4.0.2 on 2022-02-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_location_user_alter_ad_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='category_id',
            new_name='category',
        ),
    ]
