# Generated by Django 4.0.2 on 2022-03-11 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
