# Generated by Django 4.0.2 on 2022-02-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_ad_options_ad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='address',
        ),
    ]
