# Generated by Django 4.0.2 on 2022-02-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_remove_ad_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
